# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('col_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('cnt', models.IntegerField()),
                ('div', models.IntegerField()),
            ],
            options={
                'db_table': 'django_collections',
                'managed': False,
            },
        ),
    ]
