# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdustoj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionsProblem',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('col_id', models.IntegerField()),
                ('pid', models.IntegerField()),
            ],
            options={
                'db_table': 'collections_problem',
            },
        ),
        migrations.CreateModel(
            name='Compileinfo',
            fields=[
                ('solution_id', models.IntegerField(primary_key=True, serialize=False)),
                ('error', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'compileinfo',
            },
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('contest_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('defunct', models.CharField(max_length=1)),
                ('points', models.TextField(blank=True, null=True)),
                ('private', models.IntegerField()),
                ('langmask', models.IntegerField()),
                ('contest_mode', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'contest',
            },
        ),
        migrations.CreateModel(
            name='Contestinfo',
            fields=[
                ('privilege', models.CharField(blank=True, max_length=45, null=True)),
                ('contest_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('defunct', models.CharField(max_length=1)),
                ('points', models.TextField(blank=True, null=True)),
                ('langmask', models.IntegerField()),
                ('contest_mode', models.IntegerField()),
                ('language', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'contestinfo',
            },
        ),
        migrations.CreateModel(
            name='ContestPrivilege',
            fields=[
                ('privilege_id', models.AutoField(primary_key=True, serialize=False)),
                ('privilege', models.CharField(blank=True, max_length=45, null=True)),
                ('private_id', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'contest_privilege',
            },
        ),
        migrations.CreateModel(
            name='ContestProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.IntegerField()),
                ('contest_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('num', models.IntegerField()),
            ],
            options={
                'db_table': 'contest_problem',
            },
        ),
        migrations.CreateModel(
            name='ContestUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('contest_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('num', models.IntegerField()),
            ],
            options={
                'db_table': 'contest_users',
            },
        ),
        migrations.CreateModel(
            name='DjangoActivation',
            fields=[
                ('user_id', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_activation',
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language_id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.IntegerField(blank=True, null=True)),
                ('language_name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'language',
            },
        ),
        migrations.CreateModel(
            name='Loginlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('password', models.CharField(blank=True, max_length=40, null=True)),
                ('ip', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'loginlog',
            },
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('mail_id', models.AutoField(primary_key=True, serialize=False)),
                ('to_user', models.CharField(max_length=20)),
                ('from_user', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, null=True)),
                ('new_mail', models.IntegerField()),
                ('reply', models.IntegerField(blank=True, null=True)),
                ('in_date', models.DateTimeField(blank=True, null=True)),
                ('defunct', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'mail',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('time', models.DateTimeField()),
                ('release', models.IntegerField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='Online',
            fields=[
                ('hash', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=20)),
                ('ua', models.CharField(max_length=255)),
                ('refer', models.CharField(blank=True, max_length=255, null=True)),
                ('lastmove', models.IntegerField()),
                ('firsttime', models.IntegerField(blank=True, null=True)),
                ('uri', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'online',
            },
        ),
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('rightstr', models.CharField(max_length=30)),
                ('defunct', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'privilege',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('problem_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('input', models.TextField(blank=True, null=True)),
                ('output', models.TextField(blank=True, null=True)),
                ('sample_input', models.TextField(blank=True, null=True)),
                ('sample_output', models.TextField(blank=True, null=True)),
                ('spj', models.CharField(max_length=1)),
                ('hint', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('in_date', models.DateTimeField(blank=True, null=True)),
                ('time_limit', models.IntegerField()),
                ('memory_limit', models.IntegerField()),
                ('defunct', models.CharField(max_length=1)),
                ('accepted', models.IntegerField(blank=True, null=True)),
                ('submit', models.IntegerField(blank=True, null=True)),
                ('solved', models.IntegerField(blank=True, null=True)),
                ('fileupload', models.CharField(default='N', max_length=1)),
            ],
            options={
                'db_table': 'problem',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('author_id', models.CharField(max_length=20)),
                ('time', models.DateTimeField()),
                ('content', models.TextField()),
                ('topic_id', models.IntegerField()),
                ('status', models.IntegerField()),
                ('ip', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'reply',
            },
        ),
        migrations.CreateModel(
            name='Runtimeinfo',
            fields=[
                ('solution_id', models.IntegerField(primary_key=True, serialize=False)),
                ('error', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'runtimeinfo',
            },
        ),
        migrations.CreateModel(
            name='Sim',
            fields=[
                ('s_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sim_s_id', models.IntegerField(blank=True, null=True)),
                ('sim', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sim',
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('solution_id', models.AutoField(primary_key=True, serialize=False)),
                ('problem_id', models.IntegerField()),
                ('user_id', models.CharField(max_length=20)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('memory', models.IntegerField(blank=True, null=True)),
                ('in_date', models.DateTimeField(blank=True, null=True)),
                ('result', models.SmallIntegerField(blank=True, null=True)),
                ('language', models.IntegerField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=15, null=True)),
                ('contest_id', models.IntegerField(blank=True, null=True)),
                ('valid', models.IntegerField(blank=True, null=True)),
                ('num', models.IntegerField(blank=True, null=True)),
                ('code_length', models.IntegerField(blank=True, null=True)),
                ('judgetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'solution',
            },
        ),
        migrations.CreateModel(
            name='SourceCode',
            fields=[
                ('solution_id', models.IntegerField(primary_key=True, serialize=False)),
                ('source', models.TextField()),
            ],
            options={
                'db_table': 'source_code',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_id', models.IntegerField()),
                ('status', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='Statusinfo',
            fields=[
                ('solution_id', models.AutoField(primary_key=True, serialize=False)),
                ('problem_id', models.IntegerField()),
                ('user_id', models.CharField(max_length=20)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('memory', models.IntegerField(blank=True, null=True)),
                ('in_date', models.DateTimeField(blank=True, null=True)),
                ('language', models.IntegerField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=15, null=True)),
                ('contest_id', models.IntegerField(blank=True, null=True)),
                ('valid', models.IntegerField(blank=True, null=True)),
                ('num', models.IntegerField(blank=True, null=True)),
                ('code_length', models.IntegerField(blank=True, null=True)),
                ('judgetime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=45, null=True)),
                ('language_name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'statusinfo',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('status', models.IntegerField()),
                ('top_level', models.IntegerField()),
                ('cid', models.IntegerField(blank=True, null=True)),
                ('pid', models.IntegerField()),
                ('author_id', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'topic',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('submit', models.IntegerField(blank=True, null=True)),
                ('solved', models.IntegerField(blank=True, null=True)),
                ('defunct', models.CharField(max_length=1)),
                ('ip', models.CharField(max_length=20)),
                ('accesstime', models.DateTimeField(blank=True, null=True)),
                ('volume', models.IntegerField()),
                ('language', models.IntegerField()),
                ('password', models.CharField(blank=True, max_length=32, null=True)),
                ('reg_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('nick', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('activated', models.IntegerField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
