# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdustoj', '0002_collectionsproblem_compileinfo_contest_contestinfo_contestprivilege_contestproblem_contestusers_djan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginlog',
            options={'managed': False},
        ),
    ]
