# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdustoj', '0003_auto_20171114_0250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginlog',
            options={},
        ),
    ]
